services:
  airflow:
    build: .
    container_name: airflow_etl_standalone
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW_DATABASE_SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/scripts
    env_file:
      - .env
    command: airflow standalone
