services:
  spark-jupyter:
    build: .
    container_name: spark_jupyter
    ports:
      - "8888:8888" # expõe porta 8888 do Jupyter no localhost
    volumes:
      - ./notebooks:/app/notebooks
      - ./src:/app/src
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    working_dir: /app/notebooks # pasta inicial ao rodar o container
    command: >
      jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token=''
